default: build

build:
	./server.bash build

reset:
	./server.bash reset_data

start:
	./server.bash start

stop:
	./server.bash stop

clean:
	./server.bash clean

clean_data:
	./server.bash clean_data

check:
	./server.bash status
