default: build

build:
	./bdd.bash build

reset:
	./bdd.bash reset_data

start:
	./bdd.bash start

stop:
	./bdd.bash stop

clean:
	./bdd.bash clean

clean_data:
	./bdd.bash clean_data

check:
	./bdd.bash status
